version: "3"

# NETWORK
networks:
  my-network:
    driver: bridge
    
    
# VOLUMES
volumes:
  dir-site:
    driver_opts:
      device: /home/mycode/sites
      o: bind
      type: none
      
services:
# CONTAINER JAVA
  my-java:
    container_name: java-product
    build:
      dockerfile: Dockerfile
      context: ./java/
    hostname: java
    restart: always
    networks:
      - my-network
    volumes:
      - dir-site:/home/sites
    ports:
      - "80:8080"
    depends_on:
      - my-mysql
# CONTAINER MYSQL
  my-mysql:
    container_name: mysql-product
    image: "mysql:5.7.23"
    hostname: mysql
    restart: always
    networks:
      - my-network
    volumes:
      - ./db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=social
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password 